### ISSUE TITLE
compile orabbix is error

### ISSUE THREAD

**Issue by nsxq** [snickerjp/orabbix#8]
[root@zabbix orabbix]# javac -cp "orabbix-1.2.3/orabbix-1.2.3.jar:orabbix-1.2.3/lib/*" com/smartmarmot/orabbix/Sender.java
com/smartmarmot/orabbix/Sender.java:31: error: package org.apache.log4j does not exist
import org.apache.log4j.Level;
                       ^
com/smartmarmot/orabbix/Sender.java:32: error: package org.apache.log4j does not exist
import org.apache.log4j.Logger;
                       ^
com/smartmarmot/orabbix/Sender.java:34: error: package org.apache.commons.codec.binary does not exist
import org.apache.commons.codec.binary.Base64;
                                      ^
com/smartmarmot/orabbix/Sender.java:36: error: package com.smartmarmot.common does not exist
import com.smartmarmot.common.SmartLogger;
                             ^
com/smartmarmot/orabbix/Sender.java:37: error: package com.smartmarmot.zabbix does not exist
import com.smartmarmot.zabbix.ZabbixItem;
                             ^
com/smartmarmot/orabbix/Sender.java:45: error: cannot find symbol
    private static final Logger log = Logger.getLogger("Orabbix");
                         ^
  symbol:   class Logger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:47: error: cannot find symbol
    private final BlockingQueue<ZabbixItem> queue;
                                ^
  symbol:   class ZabbixItem
  location: class Sender
com/smartmarmot/orabbix/Sender.java:82: error: cannot find symbol
    public Sender(final BlockingQueue<ZabbixItem> queue,
                                      ^
  symbol:   class ZabbixItem
  location: class Sender
com/smartmarmot/orabbix/Sender.java:45: error: cannot find symbol
    private static final Logger log = Logger.getLogger("Orabbix");
                                      ^
  symbol:   variable Logger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:109: error: cannot find symbol
                final ZabbixItem item = queue.take();
                      ^
  symbol:   class ZabbixItem
  location: class Sender
com/smartmarmot/orabbix/Sender.java:117: error: cannot find symbol
	                		SmartLogger.logThis(Level.WARN,
	                		                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:117: error: cannot find symbol
	                		SmartLogger.logThis(Level.WARN,
	                		^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:125: error: cannot find symbol
	                			 SmartLogger.logThis(Level.WARN,
	                			                     ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:125: error: cannot find symbol
	                			 SmartLogger.logThis(Level.WARN,
	                			 ^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:148: error: cannot find symbol
            final ZabbixItem item = queue.remove();
                  ^
  symbol:   class ZabbixItem
  location: class Sender
com/smartmarmot/orabbix/Sender.java:156: error: cannot find symbol
            		SmartLogger.logThis(Level.WARN,
            		                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:156: error: cannot find symbol
            		SmartLogger.logThis(Level.WARN,
            		^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:166: error: cannot find symbol
            	SmartLogger.logThis(Level.WARN, "Error i didn't sent item "
            	                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:166: error: cannot find symbol
            	SmartLogger.logThis(Level.WARN, "Error i didn't sent item "
            	^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:191: error: cannot find symbol
		return new String(Base64.encodeBase64(encodeString(data)));
		                  ^
  symbol:   variable Base64
  location: class Sender
com/smartmarmot/orabbix/Sender.java:204: error: cannot find symbol
        	SmartLogger.logThis(Level.DEBUG,"sending " + message);
        	                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:204: error: cannot find symbol
        	SmartLogger.logThis(Level.DEBUG,"sending " + message);
        	^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:242: error: cannot find symbol
	            	SmartLogger.logThis(Level.DEBUG, "received "
	            	                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:242: error: cannot find symbol
	            	SmartLogger.logThis(Level.DEBUG, "received "
	            	^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:246: error: cannot find symbol
	            	SmartLogger.logThis(Level.WARN,
	            	                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:246: error: cannot find symbol
	            	SmartLogger.logThis(Level.WARN,
	            	^
  symbol:   variable SmartLogger
  location: class Sender
com/smartmarmot/orabbix/Sender.java:252: error: cannot find symbol
	        	SmartLogger.logThis(Level.ERROR,
	        	                    ^
  symbol:   variable Level
  location: class Sender
com/smartmarmot/orabbix/Sender.java:252: error: cannot find symbol
	        	SmartLogger.logThis(Level.ERROR,
	        	^
  symbol:   variable SmartLogger
  location: class Sender
28 errors

**Comment by snickerjp** [comment]
@nsxq 
Are you OK ？
